name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install
        working-directory: ./llm-geo-frontend  # ✅ Your frontend folder

      - name: 🛠️ Build the frontend
        run: npm run build
        working-directory: ./llm-geo-frontend

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./llm-geo-frontend/dist  # ✅ built files path
  
  deploy-backend-to-heroku:
      runs-on: ubuntu-latest
      needs: build-and-deploy  # Ensures frontend job finishes first
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install Heroku CLI
          run: curl https://cli-assets.heroku.com/install.sh | sh

        - name: Deploy to Heroku
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          run: |
            heroku git:remote -a dry-garden-99647  
            git push heroku main  
